projects:
  Mostpros:
    schemaPath: amplify/backend/api/Mostpros/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-north-1
        apiId: null
        maxDepth: 2
